[package]
name = "rust-raytracing-from-scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"

egui-macroquad = "0.15.0"
macroquad = "0.3.26"

